FROM python:3.12-slim

WORKDIR /app

# Evita cache de wheels e reduz imagem
ENV PIP_NO_CACHE_DIR=1

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=2800", "--server.address=0.0.0.0"]
